### PR TITLE
UNFRICKED MY THING

### PR DESCRIPTION
**Pull request by cameronsmith223**

### CODE REVIEW

**Comment by lucaswalter** [comment]
Looks good! Could you include a screenshot of the changes.

**Comment by cameronsmith223** [comment]
i did on the original issue post

**Comment by lucaswalter** [comment]
Could you add one of it running on either device or emulator? Just would like to have it documented before merging.

**Comment by cameronsmith223** [comment]
UGHHHGHGH FI)NE

**Comment by lucaswalter** [comment]
The password to get to the scribe screen is "scribe" and the password to get to the IM activity is "im"

**Comment by lucaswalter** [comment]
Testing changes now.

**Pull request merged**
