### PR TITLE
Icon artsyfartsy

### PR DESCRIPTION
**Pull request by cameronsmith223**

### CODE REVIEW

**Comment by lucaswalter** [comment]
Looks great dude, pull request set up correctly and everything!

**Comment by cameronsmith223** [comment]
Dat sheer unbounded professionalism

**Comment by lucaswalter** [comment]
Actually I lied once again... That branch extends from master instead of develop. Make sure you have develop selected on the dropdown before typing in a new branch.

**Comment by cameronsmith223** [comment]
I did though

**Comment by lucaswalter** [comment]
Call me triple liar, nevermind. The network graph was being funky earlier: https://github.com/lucaswalter/Beta-Chi-Daily-Update/network

**Pull request merged**
